name: feh-lreenaers # you probably want to 'snapcraft register <name>'
version: '2.18.3-stable' # just for humans, typically '1.2+git' or '1.3.2'
summary: feh is an X11 image viewer aimed mostly at console users
description: |
  feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. 
  It is controlled via commandline arguments and configurable key/mouse actions.
  It is released under a variant of the MIT license. For anything feh-related, you're welcome to join #feh on irc.oftc.net. https://feh.finalrewind.org/
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
  feh:
    command: usr/local/bin/feh
parts:
  feh-derf0:
    # See 'snapcraft plugins'
    source: https://feh.finalrewind.org/feh-2.18.3.tar.bz2
    plugin: make
